# Generated by Django 4.1.3 on 2022-12-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipesInfo',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='料理名')),
                ('making_time', models.CharField(max_length=100, verbose_name='作成時間')),
                ('serves', models.CharField(max_length=100, verbose_name='人数')),
                ('ingredients', models.CharField(max_length=1000, verbose_name='材料')),
                ('cost', models.CharField(max_length=100, verbose_name='コスト')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='更新日時')),
            ],
        ),
    ]
